"use client";
import { useEffect, useState } from "react";
import { resourceService } from "@/services/resourceService";
import type { Machine, ProductionLine } from "@/types";

const blank = { name: "", type: "", location: "", productionLineId: "" };
export function MachineManager() {
  const [machines,setMachines]=useState<Machine[]>([]), [lines,setLines]=useState<ProductionLine[]>([]), [form,setForm]=useState(blank), [editing,setEditing]=useState<Machine|null>(null), [open,setOpen]=useState(false), [error,setError]=useState("");
  const load=async()=>{try{const [m,l]=await Promise.all([resourceService.machines(),resourceService.productionLines()]);setMachines(m);setLines(l);}catch(e){setError(e instanceof Error?e.message:"Unable to load machines");}};
  useEffect(()=>{void load();},[]);
  const begin=(machine?:Machine)=>{setEditing(machine??null);setForm(machine?{name:machine.name,type:machine.type??"",location:machine.location??"",productionLineId:String(machine.productionLine.id)}:blank);setOpen(true);};
  const save=async(e:React.FormEvent)=>{e.preventDefault();const line=lines.find(l=>l.id===Number(form.productionLineId));if(!line)return;const body={name:form.name,type:form.type,location:form.location,productionLine:line};try{editing?await resourceService.updateMachine(editing.id,body):await resourceService.createMachine(body);setOpen(false);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to save machine");}};
  return <div className="mx-auto max-w-7xl"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-700">Asset registry</p><h1 className="mt-2 text-3xl font-bold">Machines</h1><p className="mt-2 text-sm text-slate-500">Manage equipment and its production-line assignment.</p></div><button onClick={()=>begin()} className="rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white">+ Add machine</button></div>{error&&<p className="mt-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{machines.map(machine=><article key={machine.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div className="grid size-12 place-items-center rounded-xl bg-slate-900 text-lg font-bold text-cyan-400">{machine.name.slice(0,2).toUpperCase()}</div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold text-emerald-700">Registered</span></div><h2 className="mt-5 text-lg font-bold">{machine.name}</h2><p className="mt-1 text-sm text-slate-500">{machine.type||"Unspecified machine type"}</p><dl className="mt-5 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-4 text-xs"><div><dt className="text-slate-400">Production line</dt><dd className="mt-1 font-semibold text-slate-700">{machine.productionLine.name}</dd></div><div><dt className="text-slate-400">Location</dt><dd className="mt-1 font-semibold text-slate-700">{machine.location||"—"}</dd></div></dl><div className="mt-5 flex gap-4 border-t border-slate-100 pt-4 text-sm"><button onClick={()=>begin(machine)} className="font-semibold text-cyan-700">Edit details</button><button onClick={async()=>{if(confirm(`Delete ${machine.name}?`)){await resourceService.deleteMachine(machine.id);await load();}}} className="font-semibold text-rose-600">Delete</button></div></article>)}</div>{!machines.length&&!error&&<div className="mt-8 rounded-2xl border border-dashed border-slate-300 p-16 text-center text-sm text-slate-500">No machines registered yet.</div>}
    {open&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form onSubmit={save} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><h2 className="text-xl font-bold">{editing?"Edit machine":"Add machine"}</h2><button type="button" onClick={()=>setOpen(false)} className="text-2xl text-slate-400">×</button></div><div className="mt-6 space-y-4"><label className="block text-sm font-medium">Name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 p-3" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Type<input value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 p-3" /></label><label className="text-sm font-medium">Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 p-3" /></label></div><label className="block text-sm font-medium">Production line<select required value={form.productionLineId} onChange={e=>setForm({...form,productionLineId:e.target.value})} className="mt-2 w-full rounded-xl border border-slate-200 p-3"><option value="">Select line</option>{lines.map(l=><option key={l.id} value={l.id}>{l.name} — {l.department.name}</option>)}</select></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setOpen(false)} className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold">Cancel</button><button className="rounded-xl bg-slate-900 px-5 py-2.5 text-sm font-semibold text-white">Save machine</button></div></form></div>}
  </div>;
}
